/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class Generarfactura extends javax.swing.JFrame {

    /**
     * Creates new form Generarfactura
     */
    Calendar fe=new GregorianCalendar();
    public final Menuempleados obj;
    public Generarfactura(Menuempleados obj) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        this.obj=obj;
        mostrar();
        t2.setCalendar(fe);
    }
    public void mostrar()
    {
        DefaultTableModel modelo=new DefaultTableModel();
        ResultSet re=obj.obj.n2.llenartabla("select * from facturas");
        modelo.setColumnIdentifiers(new Object[]{"idfactura","fecha","valor","idmatricula","idcliente","idmecanico"});
        try {
            while(re.next())
            {
                modelo.addRow(new Object[]{re.getInt(1),re.getString(2),re.getString(3),re.getInt(4),re.getInt(5),re.getString(6)});
            }
            tabla.setModel(modelo);
        } catch (Exception e) {
        }
    }
    public void mostrar2(String id)
    {
        DefaultTableModel modelo=new DefaultTableModel();
        ResultSet re=obj.obj.n2.llenartabla("select * from reportes where idcliente='"+id+"'");
        modelo.setColumnIdentifiers(new Object[]{"idfactura","fecha","valor","idmatricula","idcliente","idmecanico"});
        try {
            while(re.next())
            {
                modelo.addRow(new Object[]{re.getInt(1),re.getString(2),re.getString(3),re.getInt(4),re.getInt(5),re.getString(6)});
            }
            tabla.setModel(modelo);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        t2 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 103, 700, 330));

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 6, -1, -1));

        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t1KeyReleased(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 180, 35));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.darkGray);
        jLabel1.setText("IDCLIENTE:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        t2.setDateFormatString("yyyy/MM/dd HH:mm:ss");
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 47, 250, 38));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/7d514ce90eed62493f6938af1c26a477.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyReleased
        String id=t1.getText();
        mostrar2(id);
    }//GEN-LAST:event_t1KeyReleased

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        int check=2;
        int seleccionar=tabla.rowAtPoint(evt.getPoint());
        String idfactura=(String.valueOf(tabla.getValueAt(seleccionar, 0)));
        int idreporte=Integer.parseInt(idfactura);
        String fecha2=(String.valueOf(tabla.getValueAt(seleccionar, 1)));
        String valor=(String.valueOf(tabla.getValueAt(seleccionar, 2)));
        String idmatricula=(String.valueOf(tabla.getValueAt(seleccionar, 3)));
        String idcliente=(String.valueOf(tabla.getValueAt(seleccionar, 4)));
         int valorx=Integer.parseInt(valor)+10000;
        String idmecanico=(String.valueOf(tabla.getValueAt(seleccionar, 5)));
        
        String fecha=((JTextField)t2.getDateEditor().getUiComponent()).getText();
       
        obj.obj.n2.actualizavehiculo2(idmatricula, fecha);
       
        obj.mostrar();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tablaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       obj.mostrar();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private com.toedter.calendar.JDateChooser t2;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
