/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Metodossql;
import Modelo.Usuario;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class Registrarcliente extends javax.swing.JFrame {

    /**
     * Creates new form Registrarcliente
     */
    Usuario n1;
    Metodossql n2;
    public final Menuempleados obj;
    public Registrarcliente(Menuempleados obj) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        this.obj=obj;
        b2.setEnabled(false);
        
        validar();
    }
public void validar()
{
    if(t1.getText().isEmpty())
    {
        
        l1.setText("*Dato numerico*");
        b2.setEnabled(false);
    }else{
        if(obj.obj.n3.Numerico(t1.getText()))
        {
        l1.setText("");
        b2.setEnabled(true);
        }
    }
    if(t2.getText().isEmpty())
    {
        l2.setText("**");
    }else{
        l2.setText("");
    }
    if(t3.getText().isEmpty())
    {
        l3.setText("**");
    }else{
        l3.setText("");
    }
    if(t4.getText().isEmpty())
    {
        l4.setText("**");
    }else{
        l4.setText("");
    }
    if(t5.getText().isEmpty())
    {
        l5.setText("*Dato numerico*");
         b2.setEnabled(false);
    }else{
        if(obj.obj.n3.Numerico(t5.getText()))
        {
        l5.setText("");
        b2.setEnabled(true);
        }
    }
    
    
    
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t1KeyReleased(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 190, 30));

        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t2KeyReleased(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 190, 30));

        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t3KeyReleased(evt);
            }
        });
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 190, 31));

        t4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t4KeyReleased(evt);
            }
        });
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 190, 28));

        t5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t5KeyReleased(evt);
            }
        });
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 190, 29));

        jLabel1.setText("DOCUMENTO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        jLabel2.setText("NOMBRES:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        jLabel3.setText("APELLIDOS:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        jLabel5.setText("DIRECCION:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jLabel6.setText("TELEFONO:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, 16));

        b2.setText("Registrar");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 160, 40));

        b1.setText("Cancelar");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 446, -1, -1));

        l1.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 11, -1, -1));

        l2.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 22, -1, -1));

        l3.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        l4.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 58, -1, -1));

        l5.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 111, -1, -1));

        jLabel4.setText("REGISTRAR CLIENTE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 220, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/7d514ce90eed62493f6938af1c26a477.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -80, 1020, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        obj.mostrar();
        obj.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_b1ActionPerformed

    private void t1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyReleased
        validar();
    }//GEN-LAST:event_t1KeyReleased

    private void t2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyReleased
        validar();
    }//GEN-LAST:event_t2KeyReleased

    private void t3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyReleased
        validar();
    }//GEN-LAST:event_t3KeyReleased

    private void t4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t4KeyReleased
        validar();
    }//GEN-LAST:event_t4KeyReleased

    private void t5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t5KeyReleased
        validar();
    }//GEN-LAST:event_t5KeyReleased

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        String id=t1.getText();
        String nombres=t2.getText();
        String apellidos=t3.getText();
        String direccion=t4.getText();
        String telefono=t5.getText();
        String tipocliente="Normal";
        if(obj.obj.n2.buscarcliente(id).equals("no encontrado"))
        {
            obj.obj.n2.guardarcliente(id, nombres, apellidos, direccion, telefono, tipocliente);
            JOptionPane.showMessageDialog(this, "Registro exitoso");
            obj.mostrar();
            obj.setVisible(true);
            this.dispose();
        }else
        {
            JOptionPane.showMessageDialog(this, "El cliente ya se encuentra registrado");
            obj.mostrar();
            
        }
    }//GEN-LAST:event_b2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
